---
- name: Download Elasticsearch package ({{ package_url }})
  become: true
  get_url:
    url: "{{ package_url }}"
    dest: "/tmp/{{ package_url | urlsplit('path') | basename }}"
    checksum: "{{ checksum_format }}:{{ package_checksum }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"
    mode: '0775'
  register: package_tmp
  when: install_type == "package"
  tags:
    - install
    - package

- name: Install Elasticsearch rpm
  yum:
    name: "{{ package_tmp.dest }}"
    state: present
  when: install_type == "package" and ansible_os_family|lower == "redhat"
  tags:
    - install
    - package
    - redhat

- name: Install Elasticsearch debian package
  apt:
    deb: "{{ package_tmp.dest }}"
    state: present
  when: install_type == "package" and ansible_os_family|lower == "debian"
  tags:
    - install
    - package
    - debian
